//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 07:26:12 PM COT 
//


package co.edu.javeriana.tallerPica.wsdl;



public class ChargeCreditCardElement {

    protected CreditCard cc;

    /**
     * Gets the value of the cc property.
     *
     * @return
     *     possible object is
     *     {@link CreditCard }
     *
     */
    public CreditCard getCc() {
        return cc;
    }

    /**
     * Sets the value of the cc property.
     *
     * @param value
     *     allowed object is
     *     {@link CreditCard }
     *     
     */
    public void setCc(CreditCard value) {
        this.cc = value;
    }

}
