//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.23 at 07:26:12 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.creditverifier.com/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.edu.javeriana.tallerPica.wsdl;
